### ISSUE TITLE
Use unambiguous mathematical operations

### ISSUE THREAD

**Issue by klocey** [LennonLab/Emergence-Senescence#5]
@RoyBoy432 Use parentheses to ensure that python executes operations (e.g., multiplication and division) as you intend. 

https://github.com/LennonLab/Emergence-Senescence/blob/aa482bf66e9b922a94bb65b769519d04453a29d0/model/NYI_changes.py#L132

**Comment by RoyBoy432** [comment]
Thanks. Good call.
